### ISSUE TITLE
Incorrect architecture check (x86|x64)

### ISSUE THREAD

**Issue by LodewijkSioen** [hoffi/gulp-msbuild#10]
It's not you, it's [node](https://github.com/joyent/node/issues/2862).

Long story short: ```os.arch``` doesn't report the architecture of the processor, but the architecture node runs in. So if you're running node for x86 on an x64 system, ```os.arch``` will report ia32. This was the case for my (appveyor)[http://www.appveyor.com] build.

You can fix this by not using ```os.arch```, but by checking for the existence of the ```c:\Program Files (x86)\``` directory. If it exists, you'll need to look for MsBuild there, otherwise it'll be in ```c:\Program Files\```.

You can use the same check to switch between ```Framework``` and ```Framework64```

**Comment by hoffi** [comment]
Hm interesting thing.

I will use this to check for 64bit Windows:
`process.env.hasOwnProperty('ProgramFiles(x86)')`

**Comment by hoffi** [comment]
Thanks for this @LodewijkSioen :)
I have released a new version with the fix

**Comment by LodewijkSioen** [comment]
Updated, removed the hardcoded path to MsBuild, ran it trough AppVeyor and the build went green. That was quick!

:raised_hands:

**Comment by hoffi** [comment]
Great :)
