### ISSUE TITLE
Adding msbuild logging parameter

### ISSUE THREAD

**Issue by redwards1966** [hoffi/gulp-msbuild#13]
Hi, just starting to use the tool but would love a couple things added if possible.

1. Support for build logging, turning on the log and optionally setting the name ie) /flp:logfile=MyProjectOutput.log
2. An option to show the actual msbuild command that will be executed (for debugging purposes)

**Comment by hoffi** [comment]
Hey @redwards1966 
i have just created a new Version.
It is now including the options: `fileLoggerParameters`, `consoleLoggerParameters` and `logCommand` :)

**Comment by redwards1966** [comment]
Thanks, I'm going to try it out today and provide any feedback.

**Comment by redwards1966** [comment]
Works great thanks. I have another idea, I'll open on another issue.
