### ISSUE TITLE
XBuild error

### ISSUE THREAD

**Issue by gregbty** [hoffi/gulp-msbuild#16]
Using the code below, I receive the following error: 

```error
{ [Error: Command failed: /bin/sh: Build: command not found ] killed: false, code: 127, signal: null }
```

```javascript
  return gulp.src(projects) //variable that points to solution/projects
    .pipe(msbuild({
      configuration: configuration, //variable that points to either Debug or Release
      targets: ["Clean", "Build"],
      errorOnFail: true,
      stdout: true
    }));
```

I only see this error on my Mac. I do not have this issue on Windows. Any idea what's the issue?

**Comment by hoffi** [comment]
Huh..
Could you run again with the option `logCommand: true`.
Looks like the command was generated wrong.

**Comment by gregbty** [comment]
Here is the command:

"xbuild" "/path-to-sln/name.sln" /target:Clean;Build /verbosity:normal /toolsversion:4.0 /nologo /maxcpucount /property:Configuration="Development"

**Comment by hoffi** [comment]
Hm looks like the semicolon of the targets is a problem.

Can you try these: 
* Use only one Target for example: `targets: ["Rebuild"]`
* Execute the command manually but wrap the targets in double quotes: 
  * `xbuild "/path-to-sln/name.sln" /target:"Clean;Build" /verbosity:normal /toolsversion:4.0 /nologo /maxcpucount /property:Configuration="Development" `

Work both?

**Comment by gregbty** [comment]
I think both of those "work", however not I am getting the "MSBUILD0004: Too many project files specified". Have you seen that error before?

**Comment by hoffi** [comment]
Okay thanks, i will fix this.
For the error: Never heard of such an error and im also not sure what this means... Looks like a problem in the `.sln` file.

**Comment by hoffi** [comment]
The quote problem is solved.

**Comment by gregbty** [comment]
Looks like it broke the Windows msbuild system.

```error
The target "Clean;Build" does exist in project.
```

**Comment by hoffi** [comment]
Should work again with latest version
