### ISSUE TITLE
build arguments "/target: target" is broken by the latest fix

### ISSUE THREAD

**Issue by narcotics726** [hoffi/gulp-msbuild#17]
the latest commit [d9b41af693b4cae7ed78004ce56f0579f6d760b0](https://github.com/hoffi/gulp-msbuild/commit/d9b41af693b4cae7ed78004ce56f0579f6d760b0) broke msbuild

error: `The target "Clean;Build" does exist in project.`

before v0.2.10, the command was: `msbuild "targetProjectPath" /target:Clean;Build ...`
after: `msbuild "targetProjectPath" /target:"Clean;Build" ...`

the quotes around `targets` may be the problem

**Comment by bapti** [comment]
I can confirm this is also the case with my builds

**Comment by bapti** [comment]
for a quick workaround you can change your task to this

```
properties: {
        target: ['Clean;Build']
      }
```

**Comment by hoffi** [comment]
Hey, sorry for this. v0.2.11 should fix this.
Thanks to @dfal #19

**Comment by narcotics726** [comment]
All systems go!

Thanks for the rapid response. Love you guys.
