### ISSUE TITLE
Allow multiple instances to run concurrently

### ISSUE THREAD

**Issue by derekgreer** [hoffi/gulp-msbuild#21]
Currently, kicking off two tasks that use msbuild can cause the options of the last invocation to affect the first because the global options are modified.  Please change the code to use a new extended copy of options with each invocation.

**Comment by hoffi** [comment]
Hi @derekgreer, im not sure what you mean, can you show a example code of what you are doing?

**Comment by hoffi** [comment]
Nevermind, could reproduce it now.
Should be fixed with `gulp-msbuild@0.2.12`

**Comment by hoffi** [comment]
Ping @derekgreer

**Comment by derekgreer** [comment]
Thanks for the fix.
