### ISSUE TITLE
xbuild does not support the `/maxcpucount` switch

### ISSUE THREAD

**Issue by marshall007** [hoffi/gulp-msbuild#22]
If you try to run `xbuild` with the `/maxcpucount` switch, the following error is thrown:

```
MSBUILD: error MSBUILD0004: Too many project files specified
```

We need to make sure this switch doesn't get included in the command line arguments when using `xbuild`.

**Comment by hoffi** [comment]
As a workaround you can specify `maxcpucount: -1`. Then the switch will not be added to the command.

**Comment by marshall007** [comment]
@hoffi thanks for the workaround, just submitted a PR.

**Comment by hoffi** [comment]
@marshall007 thanks, merged the PR and published a new version.
