### ISSUE TITLE
Xbuild on iOS, weird error

### ISSUE THREAD

**Issue by redwards1966** [hoffi/gulp-msbuild#24]
```sh
Error: Command failed: /bin/sh -c "xbuild" "/Users/Richard/Projects/Company/marsh/marsh.social/Marsh.Social.sln" "/target:Clean;Build" /verbosity:normal /toolsversion:12.0 /nologo /flp:LogFile=build/logs/iOS.Build.log;Append;Verbosity=diagnostic /property:Configuration="Release" /property:Platform="iPhone" /property:BuildIpa="true"
/bin/sh: Append: command not found
/bin/sh: /property:Configuration=Release: No such file or directory
```

I'm getting this error after the build successfully runs through the gulp task. It's almost like there is extra commands in the stream after the build task runs and they are trying to execute. If I copy/paste that command into a command window and run it I get the same thing.

Here is my gulp task:

<pre>
gulp.task('build-ios', function() {
    return gulp
        .src('Marsh.Social.sln')
        .pipe(msbuild({
            toolsVersion: 12.0,
            targets: ['Clean', 'Build'],
						properties: { Configuration: 'Release', Platform: 'iPhone', BuildIpa: 'true' },
            errorOnFail: true,
						fileLoggerParameters: 'LogFile=build/logs/iOS.Build.log;Append;Verbosity=diagnostic',
            stdout: true
        }));
});
</pre>

**Comment by hoffi** [comment]
Hey, i have tried the command and it looks like the problem is in the `fileLoggerParameters`. 
After i put quotes around it it worked. Can you try it again with the latest version (0.2.19) ?

**Comment by redwards1966** [comment]
@hoffi Thanks for the update. I tested against the latest version and it works fine now. I guess at some point I ended up putting those double quotes in myself to get it running and forgot to update the issue. Thanks for following through on this issue. Cheers!
