### ISSUE TITLE
does not work with {read: false}

### ISSUE THREAD

**Issue by madebits** [hoffi/gulp-msbuild#25]
Hi,

In index.js you have the following code:

var stream = through.obj(function(file, enc, callback) {
    var self = this;
    if (file.isNull()) {
      self.push(file);
      return callback();
    }

you check whether the file.isNull(), which checks whether file.contents is read. For the rest of the code you only need file.path however.

The means, this lib works if gulp.src('*.sln') is called with default parameters, but does not work when you use gulp.src('*.sln', {read: false}) as optimization. 

You do not really need to real the sln contents, so it would help to replace the check of file.isNull() with something like: file && file.path.

Hope this helps.

**Comment by hoffi** [comment]
Hi,

thanks you are right. This check is not needed. I have changed it and published a new version.
