### ISSUE TITLE
0.2.14 version from NPM repo is not working

### ISSUE THREAD

**Issue by dashkodo** [hoffi/gulp-msbuild#26]
0.2.13 is working fine

**Comment by migue-pki** [comment]
Same here, reverting back to 0.2.13 fixed our problem. My environment is Win7 x64, node 0.12.4, gulp 3.9.0.

**Comment by Pondidum** [comment]
I also get this issue.
All I can figure out is that nothing seems to happen at all.

https://github.com/hoffi/gulp-msbuild/blob/master/index.js#L18 Gets run
https://github.com/hoffi/gulp-msbuild/blob/master/index.js#L23 Never seems to get invoked.

Reverting back to 0.2.13 fixes the issue also.
