### ISSUE TITLE
publish

### ISSUE THREAD

**Issue by bsjaffer** [hoffi/gulp-msbuild#27]
Is there a way to publish using publish profile?

**Comment by hoffi** [comment]
I haven't tested this, as i don't use it, but according to this [article](http://www.asp.net/mvc/overview/deployment/visual-studio-web-deployment/command-line-deployment) you need to specify two properties: `/p:DeployOnBuild=true /p:PublishProfile=Profile`

You can specify any properties in gulp-msbuild. For example: 
```javascript
msbuild({ properties: { DeployOnBuild: true, PublishProfile: "Profile" } })
```

Does this help you?

**Comment by sethkane** [comment]
@bsjaffer Did you ever get Publish profile to work?
