### ISSUE TITLE
Option to suppress 'maxcpucount' output

### ISSUE THREAD

**Issue by BryanPhelps** [hoffi/gulp-msbuild#30]
It'd be great to have an option to suppress the logging of the 'maxcpucount' option.

In the code here:
  // xbuild does not support the `maxcpucount` argument and throws if provided
  if (options.maxcpucount >= 0 && options.msbuildPath !== 'xbuild') {
    if (options.maxcpucount === 0) {
      gutil.log(gutil.colors.cyan('Using automatic maxcpucount'));
      args.push('/maxcpucount');
    } else {
      gutil.log(gutil.colors.cyan('Using maxcpucount: ' + options.maxcpucount));
      args.push('/maxcpucount:' + options.maxcpucount);
    }
  }

Perhaps by default it could be disabled, and then enabled with a verbose flag? It doesn't seem like we log other options, so disabling that logging by default seems reasonable.

The output is causing problems with some of our build tools.

For now, we are working around it by using maxcpucount: -1 as an option, but it's not ideal since it means the maxcpucount value isn't set as an argument.

Thanks!
Bryan

**Comment by hoffi** [comment]
Hi thanks! I removed logging of the `maxcpucount` completely, as i don't see any reason to do this.

**Comment by BryanPhelps** [comment]
Awesome! Thanks!
