### ISSUE TITLE
Enhancement: add some config validation and help messages

### ISSUE THREAD

**Issue by Niksko** [hoffi/gulp-msbuild#43]
Hi

It would be great if this tool warned you if you were incorrectly using invalid config values. I just spent multiple days trying to get a web publish to work, only to realise that the syntax for targets is `targets` and not `target`, and that you should be passing an array instead of just a single value.

Instead of silently choosing defaults, perhaps there should be some validation and suggestions of the value you might have been looking for?

**Comment by hoffi** [comment]
Thanks for the suggestion, i will look into it :)

**Comment by hoffi** [comment]
I have added a validation for unknown options in version 0.4.2. When a unknown option is found a suggestion is shown what the right command could be.

**Comment by julienmartin** [comment]
Hi hoffi,

Please, next time, don't do that in a patch release ! It breaks our builds where version was set to "^0.4.0".
It was more permissive before.

Julien

**Comment by hoffi** [comment]
Hey @julienmartin, what do you mean with "It was more permissive before"?

**Comment by julienmartin** [comment]
@hoffi We have a wrong parameter (projectConfiguration instead of configuration, like grunt task). Default value of configuration is Release, so no problem before, that was silent and everything worked like a charm.
For a patch release, a warning was maybe more appropriate imo.

**Comment by hoffi** [comment]
Ah ok i see. Thanks for the hint, i will notice this for the next time. 👍

**Comment by bbaia** [comment]
+1
