### ISSUE TITLE
VS 2017 Developer Command Prompt finds msbuild 14.0

### ISSUE THREAD

**Issue by arangas** [hoffi/gulp-msbuild#53]
Hello,

I'm running gulp-msbuild 0.4.7 which I think was released to fix #52.

Unfortunately I'm still having the same/similar issue:
![image](https://cloud.githubusercontent.com/assets/132198/24786189/99019b86-1b9e-11e7-8651-c0928b0900e3.png)

Happy to help diagnose if you can point me to what I should be checking for.

Thanks!

**Comment by hoffi** [comment]
gulp-msbuild checks wether one these paths exist:
- C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools
- C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise
- C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional
- C:/Program Files (x86)/Microsoft Visual Studio/2017/Community

If none of those paths exist, `gulp-msbuild` assumes it is not installed.
Can you check where your MSBuild 15 executable is located?

**Comment by arangas** [comment]
Here's what's on my machine for all `msbuild.exe` under `Program Files (x86)`:

* C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\amd64
* C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin
* C:\Program Files (x86)\MSBuild\14.0\Bin\amd64
* C:\Program Files (x86)\MSBuild\14.0\Bin

Whether I run the gulp script from a VS2015 dev command prompt, or a VS2017 command prompt, it always finds version 14.

**Comment by arangas** [comment]
I've tried to reproduce this in a clean project on that same machine but cannot, so closing this.

**Comment by Bitfiddler** [comment]
I have the same issue.  I have 2013, 2015 and 2017 installed.  The msbuild does not detect 2017 and uses 2015.  Just for fun I uninstalled 2015, now it falls back to 2013.  2017 is simply not detected and I have both paths: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools and C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional existing on my drive.

**Comment by hoffi** [comment]
Hi @Bitfiddler, this is strange, do you run any other gulp tasks before?
`gulp-msbuild` does not use any tool for the msbuild autodetection and the message you got is nowhere in the code, so I would assume this comes from any other task of your `gulpfile`.

The `msbuild` process itself would only be started between line 4 and 5.

**Comment by Bitfiddler** [comment]
Hi @hoffi , I am still fairly new to building with gulp/npm/jspm with visual studio and msbuild so I can't say for certain what's going on (I'm using a scaffold project combined from Aurelia and ServiceStack) but I did a text search for anything referencing/using msbuild and the only results were from the gulp task that runs gulp-msbuild and from the plugin itself and the visual studio project file.  Also, this auto-detection only happens when the gulp-msbuild task is in play.  If I run any of my other gulp tasks that do not in turn launch gulp-msbuild, I do not get this message.  I usually try not to label things as 'mystical', but in this case it is truly weird that this message comes up (and from the sounds of it, we are in the same boat on this).

**Comment by Bitfiddler** [comment]
Aha! perhaps I have found the culprit: gulp-nuget-restore 
This does run before my msbuild task and apparently it also uses msbuild.  I am in the process of figuring out if/how this can be fixed so as not to cause confusion in the future, but I think this line of thinking is a good bet.

**Comment by Bitfiddler** [comment]
Yep, it was gulp-nuget-restore that was the issue.  It is using it's own copy of nuget version 3.4.4 which is pre-VS2017 so it does not detect it.  I will post there.  Thanks for your time and attention @hoffi, perhaps we leave this discussion here for others in case they run into this.

**Comment by hoffi** [comment]
No problem :)

**Comment by dude0001** [comment]
@Bitfiddler did you get this resolved with gulp-nuget-restore?
