### ISSUE TITLE
`toolsVersion: 15.0` fails to find msbuild, after looking in amd64 folder

### ISSUE THREAD

**Issue by AArnott** [hoffi/gulp-msbuild#55]
In a VS 2017 developer command prompt, I can't get gulp-MSBuild util to find MSBuild.exe. It's on my PATH, but evidently the gulp task doesn't leverage that. My path is:

C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\\MSBuild\15.0\bin\MSBuild.exe

I know VS2017 provides a way to find this tool, even if it isn't on the PATH, ideally gulp-MSBuild would use that to find it rather than just checking a few common paths. But short of that, what option can I set to specify the path myself?

**Comment by AArnott** [comment]
The tool for finding VS2017 properly is documented here:

https://blogs.msdn.microsoft.com/heaths/2017/04/21/vswhere-is-now-installed-with-visual-studio-2017/

**Comment by AArnott** [comment]
It looks like this command would probably be what you want for a toolsversion:15 setting:

    "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere" -format json -latest -version "[15.0,16.0)"

Do you want me to send a PR?

**Comment by hoffi** [comment]
Hey, feel free to submit a PR. The current logic could still be kept as fallback.

**Comment by hoffi** [comment]
Fixed with #60
