### ISSUE TITLE
msBuildFromWhere Returns Path to TestAgent if Visual Studio Test Agent product is installed

### ISSUE THREAD

**Issue by baum197** [hoffi/gulp-msbuild#64]
In gulp-msbuild v0.5.4, if Visual Studio Test Agent 2017 is installed on a system, msBuildFromWhere returns the incorrect path of "c:\program files (x86)\Microsoft Visual Studio\2017\TestAgent".  This is occurs b/c the 'requires' command line switch (msbuild-finder.js ln: 14) should be '-requires' instead of 'requires'

**Comment by hoffi** [comment]
Thank you, it is fixed in Version 0.5.5
