### ISSUE TITLE
Task finished before build is complete?

### ISSUE THREAD

**Issue by royduin** [hoffi/gulp-msbuild#8]
Hi,

When I run a job with gulp-msbuild, the task is finished before the build is complete:

[14:41:19] Starting 'build'...
[14:41:19] Finished 'build' after 6.97 ms
[14:41:31] Build complete!

I'd like to run a task after the build is finished, how can I do this?

**Comment by Estyn** [comment]
I'm having the same problem, i see that there was some pull requests in the past to fix this issue, is there anything special that we need to do to run a task after the build completes?

**Comment by sirlancelot** [comment]
Are you using version `0.2.5`?

**Comment by Estyn** [comment]
I am using 0.2.5.

**Comment by royduin** [comment]
Yes, I'm using 0.2.5 too. @sirlancelot, can you give us an example how to fire an event after de build is finished?

**Comment by hoffi** [comment]
Hm, actually i'm not sure how this can be...

**Comment by sirlancelot** [comment]
You probably need to tell Gulp what the task is doing by returning the stream. Gulp will then wait to complete the task until the stream completes.

[Running tasks in series](https://github.com/gulpjs/gulp/blob/master/docs/recipes/running-tasks-in-series.md)

    gulp.task("msbuild", function() {
        return gulp.src("project.sln")
            .pipe(msbuild());
    });

**Comment by royduin** [comment]
I'll try it next week at work! Thanks!

**Comment by Estyn** [comment]
In my case it looks like the problem was something do do with my solution and custom build actions.  On a simple test project everything is working as expected, thanks for the nice plugin.

**Comment by hoffi** [comment]
@Estyn, @royduin does it work now?

**Comment by royduin** [comment]
I'll try it tomorrow, my work week starts at Tuesday.

**Comment by Estyn** [comment]
It is working for me

**Comment by royduin** [comment]
I forgot the `return`, now it's working perfectly! Thanks!

**Comment by hoffi** [comment]
Good to hear :)
